import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header, MainLayout } from "@/components";
import { cn } from "@/lib/cn";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn('flex flex-col min-h-screen', inter.className)}>
                <Header />
                <MainLayout>
                    {children}
                </MainLayout>
            </body>
        </html>
    );
}
